baseurl = "http://www.kimberlythegeek.com"
title = "Kimberly the Geek"

theme = "kimberlythegeek"
publishDir = "public_html"
languagecode = "en"

paginate = 10
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Kimberly the Geek"
    photo = "images/profile.jpg"
    description = "Kimberly Sereduck's Blog"
    keywords = "blog,developer,personal"
    info = "Software Engineer"
    caveat = "(because no one knows how to say Sereduck)"

    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = ["css/style.css"]

    # RTL support
    rtl = false


[blackfriday]
    hrefTargetBlank = true
[[params.specialties]]
  name = "Web Accessibility"
[[params.specialties]]
  name = "Test Automation"
[[params.specialties]]
  name = "Front-End Development"
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/kimberlythegeek/"
    icon = "github"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/kimberlythegeek/"
    icon = "twitter"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/kimberlythegeek/"
    icon = "linkedin"
[[menu.main]]
    name = "Home"
    weight = 1
    url  = "/"
[[menu.main]]
    name = "Posts"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    weight = 3
    name = "About"
    url = "/about/"